name: Terraform Infrastructure Deployment

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - qa
          - stg
          - prod
      action:
        description: 'Terraform action'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  TF_VERSION: '1.6.0'
  TFLINT_VERSION: 'v0.50.0'
  CHECKOV_VERSION: '3.1.0'
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      should_deploy: ${{ steps.set-env.outputs.should_deploy }}
    steps:
      - name: Determine Environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "environment=stg" >> $GITHUB_OUTPUT
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  security-scan:
    name: Security & Compliance Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'terraform/'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: false

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif

  terraform-validate:
    name: Terraform Validation & Lint
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/
        continue-on-error: false

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Initialize TFLint
        run: |
          cd terraform/environments/dev
          tflint --init

      - name: Run TFLint
        run: |
          cd terraform/environments/dev
          tflint --format compact

      - name: Terraform Init (Validation)
        run: |
          cd terraform/environments/dev
          terraform init -backend=false

      - name: Terraform Validate
        run: |
          cd terraform/environments/dev
          terraform validate

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [setup, terraform-validate]
    environment: ${{ needs.setup.outputs.environment }}
    strategy:
      matrix:
        environment: [dev, qa, stg, prod]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          cd terraform/environments/${{ matrix.environment }}
          terraform init \
            -backend-config="resource_group_name=rg-tfstate-${{ matrix.environment }}" \
            -backend-config="storage_account_name=sttfstate${{ matrix.environment }}$(echo ${{ github.repository }} | md5sum | cut -c1-8)" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform/environments/${{ matrix.environment }}
          terraform plan \
            -var-file="terraform.tfvars" \
            -out=tfplan-${{ matrix.environment }} \
            -no-color
        continue-on-error: true

      - name: Save Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: terraform/environments/${{ matrix.environment }}/tfplan-${{ matrix.environment }}
          retention-days: 5

      - name: Terraform Show
        id: show
        run: |
          cd terraform/environments/${{ matrix.environment }}
          terraform show -no-color tfplan-${{ matrix.environment }} > tfplan-${{ matrix.environment }}.txt

      - name: Comment PR with Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('terraform/environments/${{ matrix.environment }}/tfplan-${{ matrix.environment }}.txt', 'utf8');
            const truncatedPlan = plan.length > 65000 ? plan.substring(0, 65000) + '\n... (truncated)' : plan;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform Plan - ${{ matrix.environment }} Environment\n\`\`\`\n${truncatedPlan}\n\`\`\``
            });

  terraform-cost-estimation:
    name: Cost Estimation
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v4
        with:
          path: plans/

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Cost Estimate
        run: |
          infracost breakdown --path terraform/ --format json --out-file /tmp/infracost.json || true

      - name: Post Cost Comment
        if: always()
        run: |
          infracost comment github --path /tmp/infracost.json \
            --repo $GITHUB_REPOSITORY \
            --pull-request ${{ github.event.pull_request.number }} \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --behavior update || true

  terraform-test:
    name: Terraform Testing
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Terratest Unit Tests
        run: |
          cd terraform/tests
          go test -v -timeout 30m

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [setup, terraform-plan, terraform-test]
    if: |
      (github.event_name == 'push' && needs.setup.outputs.should_deploy == 'true') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
    environment: 
      name: ${{ needs.setup.outputs.environment }}
      url: ${{ steps.output.outputs.aks_fqdn }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ needs.setup.outputs.environment }}
          path: terraform/environments/${{ needs.setup.outputs.environment }}/

      - name: Terraform Init
        run: |
          cd terraform/environments/${{ needs.setup.outputs.environment }}
          terraform init \
            -backend-config="resource_group_name=rg-tfstate-${{ needs.setup.outputs.environment }}" \
            -backend-config="storage_account_name=sttfstate${{ needs.setup.outputs.environment }}$(echo ${{ github.repository }} | md5sum | cut -c1-8)" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Apply
        run: |
          cd terraform/environments/${{ needs.setup.outputs.environment }}
          terraform apply -auto-approve tfplan-${{ needs.setup.outputs.environment }}

      - name: Capture Outputs
        id: output
        run: |
          cd terraform/environments/${{ needs.setup.outputs.environment }}
          echo "aks_fqdn=$(terraform output -raw aks_cluster_fqdn)" >> $GITHUB_OUTPUT
          echo "frontdoor_endpoint=$(terraform output -raw frontdoor_endpoint)" >> $GITHUB_OUTPUT

      - name: Save Outputs
        run: |
          cd terraform/environments/${{ needs.setup.outputs.environment }}
          terraform output -json > outputs.json

      - name: Upload Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs-${{ needs.setup.outputs.environment }}
          path: terraform/environments/${{ needs.setup.outputs.environment }}/outputs.json

  post-deployment-tests:
    name: Post-Deployment Validation
    runs-on: ubuntu-latest
    needs: [setup, terraform-apply]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs-${{ needs.setup.outputs.environment }}

      - name: Validate AKS Cluster
        run: |
          az aks get-credentials --resource-group rg-aks-${{ needs.setup.outputs.environment }} --name aks-${{ needs.setup.outputs.environment }} --overwrite-existing
          kubectl get nodes
          kubectl get pods -A

      - name: Validate Front Door
        run: |
          FRONTDOOR_ENDPOINT=$(cat outputs.json | jq -r '.frontdoor_endpoint.value')
          curl -I https://$FRONTDOOR_ENDPOINT || echo "Front Door not accessible yet"

      - name: Run Smoke Tests
        run: |
          echo "Running smoke tests..."
          # Add your smoke tests here

  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [setup, terraform-apply, post-deployment-tests]
    if: always()
    steps:
      - name: Deployment Status
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ needs.terraform-apply.result }}' === 'success' ? '✅ Success' : '❌ Failed';
            console.log(`Deployment to ${{ needs.setup.outputs.environment }}: ${status}`);
